#!/bin/bash
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title Solarpanelspannung'
        echo 'graph_args --alt-y-grid --rigid --lower-limit 0 --upper-limit 25'
        echo 'graph_scale no'
        echo 'graph_vlabel Spannung in V'
        echo 'graph_category wetterstation'
        echo 'graph_info Dieses Diagramm zeigt die Solarpanelspannung der Wetterstation in V.'
        echo 'SVcc.label V'
        exit 0
fi

cat /tmp/wetterstation-solar-value
