#!/bin/bash
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title Akkuspannung'
        echo 'graph_args --alt-y-grid --rigid --lower-limit 10 --upper-limit 16'
        echo 'graph_scale no'
        echo 'graph_vlabel Spannung in V'
        echo 'graph_category wetterstation'
        echo 'graph_info Dieses Diagramm zeigt die Akkuspannung der Wetterstation in V.'
        echo 'BVcc.label V'
        exit 0
fi

cat /tmp/wetterstation-akku-value
